name: GitHub-Profile-Summary-Cards

on:
  schedule:
    # Runs at 3am JST
    - cron: '0 18 * * *' # ①
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # ②
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ③
        with:
          USERNAME: ${{ github.repository_owner }} # ④
