name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - name: Pull latest changes
        run: git pull origin main
      - name: Check for changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
          exit 0
          fi
      - name: Commit and push changes
        if: success()
        run: |
          git commit -m "Update summary cards"
          git push
